### ISSUE TITLE
webpack support

### ISSUE THREAD

**Issue by soumak77** [personality-insights/behaviors#4]
Similar request to https://github.com/personality-insights/sunburst-chart/issues/12 for making this library work with webpack

**Comment by germanattanasio** [comment]
Hey @soumak77 we are updating all the packages to use the v3 API. The Analysis we used to do on the client side with this library is now done at the service level. 

There are no plans to update this library since we want people to use v3.

**Comment by germanattanasio** [comment]
The behaviors from the API are much better than the approximation we were doing here. Remember that the service can learn and get better while this is just an approximation we were doing.

**Comment by soumak77** [comment]
@germanattanasio thanks for the feedback
